services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password11"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db